[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

[context.deploy-preview]
  command = "npm run preview"
  API_URL = "https://grupp3-jynxa.reky.se/"
